### PR TITLE
fix: button inconsistencies and sizing

### LINKED ISSUE #272: style: button sizing across the site
Buttons are a bit large, especially in comonents within a page (example: carousel). Let's either make the buttons smaller in the variants file OR change buttons to the smaller variants

### PR DESCRIPTION
**Pull request by ashleysyg**
This PR makes buttons smaller throughout the site, except for in hero. It removes a problematic h2 top margin override to improve vertical spacing on Classroom page.

### CODE REVIEW

**Comment by ccv-cj** [comment]
<p><small>Note: This comment gets updated with every commit</small></p>
<details>
<summary>
    <p>Git SHA: <code>26bc83431246b931b1c044d5e1fa673feab22b82</code></p>
    <h3>Pa11y test status: <strong>PASS</strong></h3>
</summary>
<pre><code>
{
    "total": 15,
    "passes": 15,
    "errors": 0,
    "results": {
        "http://localhost:3000/": [],
        "http://localhost:3000/about/careers": [],
        "http://localhost:3000/about/contact": [],
        "http://localhost:3000/about/us": [],
        "http://localhost:3000/mdx-editing-guide": [],
        "http://localhost:3000/services/ai-tools": [],
        "http://localhost:3000/services/classroom": [],
        "http://localhost:3000/services/oscar": [],
        "http://localhost:3000/services/project-consulting": [],
        "http://localhost:3000/services/rates": [],
        "http://localhost:3000/services/storage": [],
        "http://localhost:3000/services/storage/compare": [],
        "http://localhost:3000/services/stronghold": [],
        "http://localhost:3000/services/user-support": [],
        "http://localhost:3000/services/virtual-machine-hosting": []
    }
}

</code></pre>
</details>

File: components/storage/StorageTool.tsx [hunk 1]
```diff
@@ -60,7 +60,7 @@ export default function StorageTool({
             onAnswerChange={handleAnswerChange}
             questions={questions}
           >
-            <Button onClick={handleReset} variant="primary_outlined" size="md">
+            <Button onClick={handleReset} variant="primary_outlined" size="lg">
```
Comment (hetd54) [inline components/storage/StorageTool.tsx]: can we actually make this size sm?

File: mdx-components.tsx [hunk 2]
```diff
@@ -41,15 +41,15 @@ export function useMDXComponents(components: MDXComponents): MDXComponents {
...
+      <div className="prose prose-lg max-w-none">{children}</div>
     ),
 
     // Global MDX components
     Button: (props) => (
       <ButtonLink
         variant="primary_filled"
         size="lg"
-        className="my-4"
+        className="my-2"
```
Comment (hetd54) [inline mdx-components.tsx:52]: In your other pr you have the margin larger here

File: app/globals.css [hunk 3]
```diff
@@ -88,10 +88,6 @@
     word-wrap: break-word;
   }
 
-  .prose h2 {
-    @apply mt-0;
-  }
-
```
Comment (hetd54) [inline app/globals.css]: This was added to fix a problem with the sectionheader on prose pages, but we should just ovverride the margin-top in SectionHeader component

Screenshot 2025-09-09 at 4 02 21 PM

File: components/FeaturedCarousel.tsx [hunk 4]
```diff
@@ -167,7 +167,7 @@ export const FeaturedCarousel: React.FC<FeaturedCarouselProps> = ({
                       key={index}
                       variant={button.variant}
                       size="lg"
```
Comment (hetd54) [inline components/FeaturedCarousel.tsx]: Can we make this button smaller?

**Review by hetd54 — CHANGES_REQUESTED** [review]

File: components/storage/StorageTool.tsx [hunk 5]
```diff
@@ -49,7 +49,7 @@ export default function StorageTool({
         </p>
         <div className="hidden lg:flex lg:items-center lg:gap-4 lg:pb-8">
           <p className="text-lg">Want to dive into comparing features?</p>
-          <ScrollButton variant="primary_outlined" id="table">
+          <ScrollButton variant="primary_outlined" size="lg" id="table">
```
Comment (hetd54) [inline components/storage/StorageTool.tsx]: This is too big haha

Screenshot 2025-09-09 at 4 30 24 PM

File: components/storage/StorageTool.tsx (hunk 1 above)
Comment (ashleysyg) [reply components/storage/StorageTool.tsx]: it doesn't pass accessibility tests when it is sm... i could try primary_filled?

File: components/button/variants.tsx [hunk 6]
```diff
@@ -84,9 +87,9 @@ export const ButtonVariants = cva(
 
     defaultVariants: {
       variant: "primary_filled",
-      size: "default",
+      size: "md",
```
[the remark this answers is not in the document]
Comment (ashleysyg) [reply components/button/variants.tsx:90]: i personally prefer calling the default size "md" so it fits in with the t shirt sizing convention.... i am open to changing md to default though if people think it's a better idea to have an explicit default size

**Review by hetd54 — APPROVED** [review]
Looks good! Double checked with wave and pa11y

Screenshot 2025-09-16 at 9 47 03 AM
