### PR TITLE
Fix mobile overflow

### LINKED ISSUE #483: bug: request an oscar account button on mobile is too big
Image

### PR DESCRIPTION
**Pull request by hetd54**
Removes the big oscar button on mobile, shortens text on buttons as needed

### CODE REVIEW

**Comment by ccv-cj** [comment]
<p><small>Note: This comment gets updated with every commit</small></p>
<details>
<summary>
    <p>Git SHA: <code>1157474d4ca7e313eb402c7af763032abcf4bb20</code></p>
    <h3>Pa11y test status: <strong>PASS</strong></h3>
</summary>
<pre><code>
{
    "total": 17,
    "passes": 17,
    "errors": 0,
    "results": {
        "http://localhost:3000/": [],
        "http://localhost:3000/about/careers": [],
        "http://localhost:3000/about/grant-and-publication-materials": [],
        "http://localhost:3000/about/help": [],
        "http://localhost:3000/about/us": [],
        "http://localhost:3000/ai/ai-oscar": [],
        "http://localhost:3000/ai/ai-tools": [],
        "http://localhost:3000/mdx-editing-guide": [],
        "http://localhost:3000/services/classroom": [],
        "http://localhost:3000/services/department-support": [],
        "http://localhost:3000/services/oscar": [],
        "http://localhost:3000/services/project-consulting": [],
        "http://localhost:3000/services/rates": [],
        "http://localhost:3000/services/storage": [],
        "http://localhost:3000/services/stronghold": [],
        "http://localhost:3000/services/virtual-machine-hosting": [],
        "http://localhost:3000/services/workshops": []
    }
}

</code></pre>
</details>

File: components/LocationSection.tsx [hunk 1]
```diff
@@ -43,7 +43,7 @@ export function LocationSection({ className }: LocationSectionProps) {
             href="https://en.wikipedia.org/wiki/Brown_University_Computing_Laboratory"
             className="mx-auto my-2 w-auto"
           >
-            Brown University Computing Laboratory
+            Computing Laboratory
```
Comment (eldu) [inline components/LocationSection.tsx:46]: This is fine! Just throwing a suggestion out there. Not sure if this is any better though

```suggestion
            Read More
```

**Review by eldu — APPROVED** [review]
Thanks Heather!

File: components/LocationSection.tsx (hunk 1 above)
Comment (hetd54) [reply components/LocationSection.tsx:46]: We should avoid "Read More" and "Learn More" and "Click Here" type things bc accessibility
