### PR TITLE
fix mobile views

### LINKED ISSUE #147: fix: mobile view
Mobile view has different issues across different pages. Do a sweep and make PRs for them

### PR DESCRIPTION
**Pull request by ashleysyg**
page/component specific:
- [x] about/contact: contact us section cards need x-gap
- [x] about/us: our mission and People section headers overlapping with text above and below
- [x] services/classroom: overlaps with section above and below
- [x] services/storage/compare: badges spilling out of cards
- [x] services/rates: make unreplicated/replicated card width the same
- [x] status banner: add text back and vertically center text and button to status website

featured carousel: 
- [x] swipeable cards in mobile
- [x] remove image in mobile
- [x] move the buttons and pagination dots to the top center of the card so the card can still be responsive size while the buttons stay in the same y coordinate on the page
- [x] add max-width and centered the carousel on the page.

general:
- [x] make all buttons smaller and adjust size with screen size
- [x] button wrap with small screens (oscar, storage, classroom)
- [x] standardize left and right page margins and reduce for smaller screens
- [x] reduce text size for smaller screens at same breakpoints as margin changes

***classroom, oscar, storage, compare, rates may all be affected by switching to mdx. fix in new PR if so.

### CODE REVIEW

**Comment by ashleysyg** [comment]
Screenshot 2025-07-22 at 11 00 11 AM
Screenshot 2025-07-22 at 10 59 42 AM

I ended up changing the carousel design for this PR. I'm open to aesthetic feedback because it is quite different. I enclosed the carousel in a card to add visual contrast with the white background (there is a separate PR to remove the shadow from the cards so it is just a gray outline around it). I moved the left/right buttons to the top because it was difficult to keep the card/carousel size responsive while keeping the arrows in the same place so clicking through isn't annoying. i tried added a fixed height and keeping the buttons below the carousel, but had a lot of issues finding a height that made sense for mobile view. the cards either had a lot of awkward white space at the bottom (for cards with less content), or the content was spilling out of smaller fixed height.

**Comment by ashleysyg** [comment]
Screenshot 2025-07-22 at 11 08 58 AM

I believe this issue with the white box around the text is a product of how the yaml files are rendered using complicated logic. once i convert these content pages to MDX, this should be resolved.

**Comment by ashleysyg** [comment]
okay i'm now ready for review sorry i realized there were still a bunch of incosistencies across pages!

**Review by hetd54 — CHANGES_REQUESTED** [review]
This looks SO much better!! A few things to tackle:

# Home

If I make the page taller than wide on desktop, the buttons are covered up!

Screenshot 2025-07-25 at 12 13 57 PM

# Home and Classroom

The swipe works well, but it isn't clear that you CAN do that as a user. One assumes that you have to scroll down to see what you are looking at, and then scroll back up to tap on the next button. I liked @gtdang 's idea of seeing the edge of the next card to indicate this. We might want to make the card text a bit smaller or something to accommodate that? 


Screenshot 2025-07-25 at 12 07 01 PM

# About

Something on the Us page is causing some overflow. An idea is to make the avatar photos a bit smaller? Not sure. View is for Samsung Galaxy 8

Screenshot 2025-07-25 at 12 09 24 PM

**Comment by ashleysyg** [comment]
Thank you Heather!! I updated the People Cards and Hero Cards! I'll make another PR for the Carousel swiping?

File: app/services/rates/page.tsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ export default async function Rates() {
       />
 
       {/* Oscar */}
-      <section className="content-wrapper py-24 px-14 lg:px-36">
+      <section className="content-wrapper py-24">
```
Comment (hetd54) [inline app/services/rates/page.tsx]: Why not use the Content Section ui component instead of section tags?

File: components/ui/variants.tsx [hunk 2]
```diff
@@ -63,9 +63,9 @@ export const buttonVariants = cva(
         default: "h-9 px-6 py-6 text-xl",
         sm: "h-8 px-3 py-3 text-xs",
         md: "h-8 px-6 py-6 text-md",
-        lg: "h-10 px-8 py-8 text-2xl",
-        xl: "h-14 px-8 py-8 text-2xl",
-        xxl: "h-16 px-10 py-10 text-3xl",
+        lg: "h-8 px-6 py-6 text-md sm:h-10 sm:px-8 sm:py-8 sm:text-2xl",
+        xl: "h-8 px-6 py-6 text-md sm:h-14 sm:px-8 sm:py-8 sm:text-2xl",
+        xxl: "h-8 px-6 py-6 text-md sm:h-16 sm:px-10 sm:py-10 sm:text-3xl",
```
Comment (hetd54) [inline components/ui/variants.tsx:69]: love the addition of adding separate padding/text size for smaller screens versus larger

File: components/ui/variants.tsx [hunk 3]
```diff
@@ -1,7 +1,7 @@
 import { cva, VariantProps } from "class-variance-authority"
 
 export const buttonVariants = cva(
-  "inline-flex items-center justify-center flex-shrink-0 whitespace-nowrap w-auto mr-6 font-semibold rounded-full transition-colors focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 [&_svg]:pointer-events-none",
+  "inline-flex items-center justify-center flex-shrink-0 whitespace-nowrap w-full sm:w-auto mr-6 font-semibold rounded-full transition-colors focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 [&_svg]:pointer-events-none",
```
Comment (hetd54) [inline components/ui/variants.tsx]: the ```sm:w-auto``` addition here causes repeated code in a lot of places -- example: EventSection.tsx, the button there also has ```className="mt-0 sm:w-auto"``` -- can we go through and remove the repetition in other places? Having it here only makes sense!

File: components/storage/StorageTool.tsx [hunk 4]
```diff
@@ -31,10 +31,10 @@ export default function StorageTool({ pageContent, questions, initialSelectedAns
     
     return (
         <div>
-            <section className="content-wrapper py-24 px-8 bg-white">
+            <section className="content-wrapper py-24 bg-neutral-50">
```
Comment (hetd54) [inline components/storage/StorageTool.tsx]: Why not content-section component here?

File: components/storage/StorageServiceCard.tsx [hunk 5]
```diff
@@ -52,20 +52,22 @@ const StorageServiceCard: React.FC<ServiceCardProps> = ({ service, questionsConf
...
 
             return (
-              <div key={feature.name} className="space-y-1">
-                {/* Main feature row with icon, name, and badge */}
-                <div className="flex items-center gap-2 text-neutral-500 font-semibold tracking-wide min-w-0">
+              <div key={feature.name} className="space-y-2">
+                {/* Feature name and icon */}
+                <div className="flex items-center gap-2 text-neutral-500 font-semibold tracking-wide">
                   {IconComponent ? <IconComponent className="text-lg flex-shrink-0" /> : null}
                   <span className="flex-shrink-0">{humanize(feature.name).toUpperCase()}:</span>
```
Comment (hetd54) [inline components/storage/StorageServiceCard.tsx]: Why do we have ```flex-shrink-0``` here? This causes text not to wrap for the name. Let me know if I am missing something.

Screenshot 2025-07-28 at 11 21 13 AM

File: components/EventSection.tsx [hunk 6]
```diff
@@ -98,10 +98,10 @@ export function EventSection({
   const CAL_VIEW_ARRAY = ["Upcoming", "Weekly", "Monthly"] as const
 
   return (
-    <section className="content-wrapper m-0">
+    <section className="m-0">
```
Comment (hetd54) [inline components/EventSection.tsx]: Sorry if this was leftover from me, but we can also remove ```m-0``` here since we aren't having to override the content-wrapper class

File: components/EventSection.tsx [hunk 7]
```diff
@@ -110,7 +110,7 @@ export function EventSection({
       </div>
 
       {/* Large Screen Layout (Desktop) */}
```
Comment (hetd54) [inline components/EventSection.tsx:102]: Why are the small screen and large screen divs/EventCard separated here? Wouldn't it be more tree-efficient to have them be the same with tailwind properties specifying screen-specific differences?

File: components/LayoutWithStatusBanner.tsx [hunk 8]
```diff
@@ -37,10 +37,10 @@ export default function LayoutWithStatusBanner({ issues }: LayoutWithStatusBanne
               </>
             ) : (
               <>
-                <p className="text-lg">
+                <p className="text-xs sm:text-sm md:text-lg whitespace-nowrap">
                   All Services Operational
                 </p>
-                <Button variant="secondary_filled" size="sm" className="text-lg">
+                <Button variant="secondary_filled" size="sm" className="text-xs sm:text-sm md:text-lg m-0">
```
Comment (hetd54) [inline components/LayoutWithStatusBanner.tsx]: Is ```m-0``` necessary here?

File: components/LayoutWithStatusBanner.tsx [hunk 9]
```diff
@@ -20,13 +20,13 @@ export default function LayoutWithStatusBanner({ issues }: LayoutWithStatusBanne
...
-          <div className="flex flex-wrap items-center gap-x-4">
+          <div className="flex items-center justify-center gap-x-4 min-w-0 w-full">
             {issues.length > 0 ? (
               <>
-                <p className="text-lg">
+                <p className="text-xs sm:text-sm md:text-lg">
                   <strong>Service Disruption:</strong> {repoNames}
                 </p>
-                <Button variant="secondary_filled" size="sm" className="text-md">
+                <Button variant="secondary_filled" size="sm" className="text-xs sm:text-sm md:text-md m-0">
```
Comment (hetd54) [inline components/LayoutWithStatusBanner.tsx]: Is ```m-0``` necessary here?

File: components/StatusBanner.tsx
Comment (hetd54) [inline components/StatusBanner.tsx:1]: Something is funky here. I'm suspecting something with the flex shrink rules

Screenshot 2025-07-28 at 11 41 56 AM

File: components/storage/StorageForm.tsx [hunk 10]
```diff
@@ -14,7 +14,7 @@ interface FormProps {
 
 const Form: React.FC<FormProps> = ({ selectedAnswers, onAnswerChange, questions }) => {
   return (
-    <div className="space-y-2 px-8 pb-8 bg-gradient-to-br from-white to-neutral-50/30 rounded-2xl max-w-[800px] border border-neutral-300">
+    <div className="space-y-2 px-[4vw] sm:px-[3vw] md:px-8 pb-8 bg-gradient-to-br from-white to-neutral-50/30 rounded-2xl max-w-[800px] border border-neutral-300">
```
Comment (hetd54) [inline components/storage/StorageForm.tsx]: What's the reason for using ```vw``` for the padding for smallest screen size and then back to tailwind's calc for bigger?

File: components/FeaturedCarousel.tsx [hunk 11]
```diff
@@ -47,38 +48,85 @@ export const FeaturedCarousel: React.FC<FeaturedCarouselProps> = ({
...
+        {/* Carousel Container */}
+        <div className="bg-white relative" {...handlers}>
+          {/* Navigation Buttons */}
+          <div className="flex justify-center items-center gap-4">
+            <Button
+              variant="secondary_filled"
+              size="icon"
+              aria-label="previous project"
+              onClick={prev}
+              className="w-[40px] h-[40px] !mr-0"
```
Comment (hetd54) [inline components/FeaturedCarousel.tsx]: I'm not seeing a difference when I remove this class -- can you post a screencap of what this is doing?

**Review by hetd54 — CHANGES_REQUESTED** [review]
I did my best here looking through the code but this may benefit from a second pair of eyes!

File: app/services/rates/page.tsx (hunk 1 above)
Comment (ashleysyg) [reply app/services/rates/page.tsx]: Good catch! But, also, the refactor-yaml PR makes all this code obsolete since the rates sections and their separate content files will be in a single MDX there. I'll change this anyway though for our records...

File: components/ui/variants.tsx (hunk 3 above)
Comment (ashleysyg) [reply components/ui/variants.tsx]: nice! done

File: components/storage/StorageServiceCard.tsx (hunk 5 above)
Comment (ashleysyg) [reply components/storage/StorageServiceCard.tsx]: Oh yes... the margins are weird here also. on it!

File: components/LayoutWithStatusBanner.tsx (hunk 9 above)
Comment (ashleysyg) [reply components/LayoutWithStatusBanner.tsx]: nope! removed.

File: components/storage/StorageForm.tsx (hunk 10 above)
Comment (ashleysyg) [reply components/storage/StorageForm.tsx]: yes so true. changed.

File: components/FeaturedCarousel.tsx (hunk 11 above)
Comment (ashleysyg) [reply components/FeaturedCarousel.tsx]: only !mr-0 is needed. the button component has a right margin. that shoudl probably be refactored so we're using gap maybe. i think that's why i did it

File: components/StatusBanner.tsx
Comment (ashleysyg) [reply components/StatusBanner.tsx:1]: fixed! i had to override the mobile button behavior for just this one. otherwise, i like the buttons as full width

File: components/EventSection.tsx (hunk 7 above)
Comment (ashleysyg) [reply components/EventSection.tsx:102]: oh you are so right. i refactored with component and the status banner component because they were both really repetitive and nested.

**Comment by ashleysyg** [comment]
Heather, you are a rockstar reviewer! I made a ton of improvements based on ur suggested changes!

**Comment by ccv-cj** [comment]
<p><small>Note: This comment gets updated with every commit</small></p>
<details>
<summary>
    <p>Git SHA: <code>89bfb7910e796512bfb4f41b8cf411aa7bd211ea</code></p>
    <h3>Pa11y test status: <strong>PASS</strong></h3>
</summary>
<pre><code>
{"status": "success", "message": "No accessibility issues found!", "results": []}

</code></pre>
</details>

**Comment by ashleysyg** [comment]
I was in merge conflict hell because of... you guessed it... ButtonLink. One last thing - BrownBanner - is messed up. Resizing/mobile view needs work with the Brown Logo svg, but that has to be another PR or I'll die.

File: components/BrownBanner.tsx [hunk 12]
```diff
@@ -1,24 +1,23 @@
...
 interface BrownBannerProps {
   id?: string
 }
 
-export const BrownBanner: React.FC<BrownBannerProps> = ({ id }) => {
+export const BrownBanner: React.FC<BrownBannerProps> = () => {
   return (
-    <header className="content-wrapper bg-white flex items-center py-2">
+
+    <header className="bg-white flex items-center py-2 px-6">
```
Comment (hetd54) [inline components/BrownBanner.tsx:13]: You are hiding everything up here on mobile, right? Why don't we apply hidden at this header level instead?

**Review by hetd54 — APPROVED** [review]
Looks good! See my one comment if it actually is true to what you are wanting to do

File: components/BrownBanner.tsx (hunk 12 above)
Comment (ashleysyg) [reply components/BrownBanner.tsx:13]: i want to hide everythign except for the brown logo. the issues right now are that it is getting cut off on the top and bottom starting lg or md, and cut off and centered in mobile view. i want it to be a small logo on the left
