### PR TITLE
fix: make event fetching client side so it fetches on page load

### LINKED ISSUE #359: Events page shows past events
I just noticed that the events page includes past events. Can we please make sure to filter the past events?

### PR DESCRIPTION
**Pull request by gtdang**
Makes the event fetch client-side so that it fetches on page load. Copilot helped a lot on this one because use effects 🤯.

closes #359

### CODE REVIEW

**Comment by ccv-cj** [comment]
<p><small>Note: This comment gets updated with every commit</small></p>
<details>
<summary>
    <p>Git SHA: <code>f286c12ce7bb470d08ef84e8a0a00075edc1eeed</code></p>
    <h3>Pa11y test status: <strong>PASS</strong></h3>
</summary>
<pre><code>
{
    "total": 17,
    "passes": 17,
    "errors": 0,
    "results": {
        "http://localhost:3000/": [],
        "http://localhost:3000/about/careers": [],
        "http://localhost:3000/about/contact": [],
        "http://localhost:3000/about/us": [],
        "http://localhost:3000/ai/ai-oscar": [],
        "http://localhost:3000/ai/ai-tools": [],
        "http://localhost:3000/mdx-editing-guide": [],
        "http://localhost:3000/services/classroom": [],
        "http://localhost:3000/services/department-support": [],
        "http://localhost:3000/services/oscar": [],
        "http://localhost:3000/services/project-consulting": [],
        "http://localhost:3000/services/rates": [],
        "http://localhost:3000/services/storage": [],
        "http://localhost:3000/services/storage/compare": [],
        "http://localhost:3000/services/stronghold": [],
        "http://localhost:3000/services/user-support": [],
        "http://localhost:3000/services/virtual-machine-hosting": []
    }
}

</code></pre>
</details>

File: app/page.tsx [hunk 1]
```diff
@@ -58,12 +47,7 @@ export default async function Home() {
           </ContentSection>
           <ContentSection title={"Events"} align={"left"} id={"events"}>
             <Suspense fallback={<Spinner />}>
-              <EventSection
-                streamedDataPast={pastDates}
-                streamedDataFuture={futureDates}
-                currentDate={currentDate}
-                today={today}
-              />
+              <EventSectionClient />
```
Comment (anna-murphy) [inline app/page.tsx]: This was all previously in a `<Suspense />` but I think you can remove that now that this is a client component!

File: components/EventSection.tsx [hunk 2]
```diff
@@ -22,8 +22,8 @@ export interface DataProps {
 }
 
 interface EventSectionProps {
-  streamedDataFuture: Promise<any>
-  streamedDataPast: Promise<any>
+  streamedDataFuture: any[]
+  streamedDataPast: any[]
```
Comment (anna-murphy) [inline components/EventSection.tsx]: If it was up to me, I'd love to have a better sense of what this type actually is -- maybe not for this PR given that it was previously `Promise<any>`, but if you have bandwidth in the future, sounds like a decent small tech-debt item to handle.

File: components/EventSectionClient.tsx [hunk 3]
```diff
@@ -0,0 +1,47 @@
+"use client"
+
+import React, { useEffect, useState } from "react"
+import { getEventData } from "@/app/queries"
+import { getStringDate } from "@/components/calendar/utils"
+import EventSection from "@/components/EventSection"
+import Spinner from "@/components/assets/Spinner"
+
+export default function EventSectionClient() {
```
Comment (anna-murphy) [inline components/EventSectionClient.tsx:8]: I like this a lot! There's a part of me that does wonder if this can be modularized, but I think that's something for me to think about later 📝

File: components/EventSectionClient.tsx [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+  const [loading, setLoading] = useState(true)
+
+  useEffect(() => {
+    const now = new Date()
+    setCurrentDate(now)
+    const todayStr = getStringDate(
+      now.getMonth() + 1,
+      now.getDate(),
+      now.getFullYear()
+    )
```
Comment (anna-murphy) [inline components/EventSectionClient.tsx]: A small thing for me is that when I'm doing this kind of date manipulation, I tend to get nervous -- everything feels like it's magic numbers and I just don't like it. *If* you feel the same way, I have two suggestions for you. So I have two suggestions for you:
1. Are you using `date-fns`? If so, they probably have a function to do the work you're looking to do.
2. If not, the ISO Date String is a standard spec, so you can do some silly string parsing to get the values you want out of the ISO Date String:

```js
const [date, month, year] = date.toISOString().split("T")[0].split("-");
```

File: components/EventSectionClient.tsx [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+import Spinner from "@/components/assets/Spinner"
+
+export default function EventSectionClient() {
+  const [futureDates, setFutureDates] = useState<any>(null)
+  const [pastDates, setPastDates] = useState<any>(null)
+  const [currentDate, setCurrentDate] = useState<Date | null>(null)
+  const [today, setToday] = useState<string>("")
+  const [loading, setLoading] = useState(true)
+
+  useEffect(() => {
```
Comment (anna-murphy) [inline components/EventSectionClient.tsx:23]: This looks good! I think if I was writing this function I would have implemented it _slightly_ different. I don't love defining functions in-line like you did here, even though it's not abnormal in `useEffect`s specifically. Instead, I'd move the function outside the component, and have it return past and future dates that you can set to React state in the promise callback.

Here's kind of what I mean:

```js
async function fetchData(today: string) {
  const future = await getEventData(today)
  const past = await getEventData(`-2 months${today}`)
  return [future, past]
}

// In the component...

useEffect(() => {
  setLoading(true)
  const todayStr = makeTodayStr() // However you want to do this
  fetchData(todayStr).then(([future, past]) => {
    setFutureDates(future)
    setPastDate(past)
    setLoading(false)
  })
}, [])
```

These are logically equivalent, but I think it's easier (for me) to read.

File: components/EventSectionClient.tsx [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+      now.getMonth() + 1,
+      now.getDate(),
+      now.getFullYear()
+    )
+    setToday(todayStr)
+
+    const fetchData = async () => {
+      setLoading(true)
+      const future = await getEventData(todayStr)
+      const past = await getEventData(`-2 months${todayStr}`)
```
Comment (anna-murphy) [inline components/EventSectionClient.tsx]: Fun JS trick! These requests are made in sequence. You fetch one, wait for a response, then fetch a second one and wait for a response. Probably doesn't matter here, but you can speed up your code like this:

```js
const [future, past] = await Promise.all([getEventData(todayStr), getEventData(`-2 months${todayStr}`)])
setFutureDates(future)
// ...
```

This makes your first request, then makes your second request, and then waits for both to return, and then continues execution. Fun!

**Review by anna-murphy — COMMENTED** [review]
Hi George! @eldu let me know you were waiting on a second pair of eyes on this code, and said I might be able to help! I added a few comments that are mostly stylistic -- your solution looks pretty good to me! You're welcome to take anything here you want if it'll be useful, but don't feel obligated to accept all my comments.

Btw, @eldu mentioned this was because you were noticing that NextJS was fetching during build time and baking the data into the application. We ran into this problem over on the RIDDC project, and I solved it in a slightly different way there: https://github.com/ridatadiscoverycenter/riddc-dashboard/pull/112 You should be able to tell NextJS to force a rerender of the page every page load. For your case, I actually prefer your solution here (this is just one small component on the main page -- you want the main page to be fast), but if you want to have this tool in your toolbox, it might come in handy as well.

**Comment by gtdang** [comment]
Wow! Thanks for all the great input @anna-murphy!

File: components/EventSectionClient.tsx (hunk 4 above)
Comment (gtdang) [reply components/EventSectionClient.tsx]: Oh! It seems that `getStringDate` is just a custom utility to do `date.toISOString().split("T")[0]`. So we can just ❌ all of that!

**Review by hetd54 — APPROVED** [review]
ty George!
