### PR TITLE
fix: moves career fetching client side

### LINKED ISSUE #447: bug: make workday fetch client side
Similar to #446. We need to make the workday fetch client-side instead of server side so that it fetches on page load.

### PR DESCRIPTION
**Pull request by gtdang**
* moved CareerData component into its own file 
* created an API route for querying careers to not expose cookie

closes  #447

### CODE REVIEW

**Comment by ccv-cj** [comment]
<p><small>Note: This comment gets updated with every commit</small></p>
<details>
<summary>
    <p>Git SHA: <code>46335cf29585a2c19973ac9bfd38e72b8b080adb</code></p>
    <h3>Pa11y test status: <strong>PASS</strong></h3>
</summary>
<pre><code>
{
    "total": 17,
    "passes": 17,
    "errors": 0,
    "results": {
        "http://localhost:3000/": [],
        "http://localhost:3000/about/careers": [],
        "http://localhost:3000/about/contact": [],
        "http://localhost:3000/about/grant-and-publication-materials": [],
        "http://localhost:3000/about/us": [],
        "http://localhost:3000/ai/ai-oscar": [],
        "http://localhost:3000/ai/ai-tools": [],
        "http://localhost:3000/mdx-editing-guide": [],
        "http://localhost:3000/services/classroom": [],
        "http://localhost:3000/services/department-support": [],
        "http://localhost:3000/services/oscar": [],
        "http://localhost:3000/services/project-consulting": [],
        "http://localhost:3000/services/rates": [],
        "http://localhost:3000/services/storage": [],
        "http://localhost:3000/services/stronghold": [],
        "http://localhost:3000/services/user-support": [],
        "http://localhost:3000/services/virtual-machine-hosting": []
    }
}

</code></pre>
</details>

File: app/api/workday/route.ts [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import { getWorkdayData } from "@/app/about/queries"
```
Comment (eldu) [inline app/api/workday/route.ts]: Looks like `getWorkdayData` is the only thing in that queries file. I'd suggest moving it into this file instead to keep everything together.

File: app/api/workday/route.ts [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+
+interface WorkdayRequest extends Request {}
```
Comment (eldu) [inline app/api/workday/route.ts]: WorkdayRequest is extending Request... but there isn't any modifications. This could be deleted, and then you could use `Request` a few lines below

File: app/api/workday/route.ts [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+
+type WorkdayResponse = Response
+
+export async function GET(req: WorkdayRequest): Promise<WorkdayResponse> {
```
Comment (eldu) [inline app/api/workday/route.ts]: I believe this could just be this

```suggestion
export async function GET(req: Request): Promise<Response> {
```

File: app/api/workday/route.ts [hunk 4]
```diff
@@ -0,0 +1,12 @@
+import { getWorkdayData } from "@/app/about/queries"
+
+interface WorkdayRequest extends Request {}
+
+type WorkdayResponse = Response
```
Comment (eldu) [inline app/api/workday/route.ts]: We could just use the `Response` as the type and remove this line

File: app/api/workday/route.ts (hunk 1 above)
Comment (eldu) [reply app/api/workday/route.ts]: (Also not part of this PR, but I'm realizing the getEventData is also off on a file on it's own. I'd also tie that closer to the rest of the relevant code!)

**Review by eldu — CHANGES_REQUESTED** [review]
I just got some reorganization requests

**Review by eldu — APPROVED** [review]
thanks george !
