### PR TITLE
Fix replace speech icon

### LINKED ISSUE #436: speech bubble icons
Speech bubble icons have a connotation with chatbots or a chat support feature now. We should definitely use a different icon with the header "Work With Us" button (perhaps handshake?). The icon also appears in the Nav menu for "Project Consulting" and "Contact Us". I think it's fine for "Project Consulting", but maybe change "Contact Us" to an envelope or keyboard icon?

### PR DESCRIPTION
**Pull request by gtdang**
This is to move away from the bubble chat icon which often has the connotation of a chat support/chatbot. 

**Changes:**
1. Banner _Work With Us_ -> handshake 
2. Navbar _Contact Us_ -> envelope 
3. Navbar _Project Consulting_ -> compass 

Open to keeping 2 or 3 as the FaComments. I don't love the handshake but that one needs to change. Open to other suggestions. 

closes #436

### CODE REVIEW

**Comment by ccv-cj** [comment]
<p><small>Note: This comment gets updated with every commit</small></p>
<details>
<summary>
    <p>Git SHA: <code>fba48860b153e1031d80d1559615b8a5ad274d78</code></p>
    <h3>Pa11y test status: <strong>PASS</strong></h3>
</summary>
<pre><code>
{
    "total": 17,
    "passes": 17,
    "errors": 0,
    "results": {
        "http://localhost:3000/": [],
        "http://localhost:3000/about/careers": [],
        "http://localhost:3000/about/contact": [],
        "http://localhost:3000/about/us": [],
        "http://localhost:3000/ai/ai-oscar": [],
        "http://localhost:3000/ai/ai-tools": [],
        "http://localhost:3000/mdx-editing-guide": [],
        "http://localhost:3000/services/classroom": [],
        "http://localhost:3000/services/department-support": [],
        "http://localhost:3000/services/oscar": [],
        "http://localhost:3000/services/project-consulting": [],
        "http://localhost:3000/services/rates": [],
        "http://localhost:3000/services/storage": [],
        "http://localhost:3000/services/storage/compare": [],
        "http://localhost:3000/services/stronghold": [],
        "http://localhost:3000/services/user-support": [],
        "http://localhost:3000/services/virtual-machine-hosting": []
    }
}

</code></pre>
</details>

File: components/BrownBanner.tsx [hunk 1]
```diff
@@ -31,8 +31,8 @@ export const BrownBanner: React.FC<BrownBannerProps> = () => {
         size="sm"
         className={"px-2 py-6 sm:px-4"}
       >
-        <FaComments className="text-lg sm:text-xl" />
-        Work with Us
+        <FaHandshake className="text-lg sm:text-2xl" />
+        Work With Us
```
Comment (eldu) [inline components/BrownBanner.tsx:35]: I liked the previous casing.. but am I wrong??? I have no idea. I'm reading this [blog post](https://titlecaseconverter.com/blog/is-with-capitalized/) and now i don't know

```suggestion
        Work with Us
```

**Review by eldu — APPROVED** [review]
approving, but i did add a suggestion

File: components/BrownBanner.tsx (hunk 1 above)
Comment (gtdang) [reply components/BrownBanner.tsx:35]: I kind of like it capitalized but I don't really feel strongly about it. Seems like we can go either way according to that post.
