### PR TITLE
Fix  storage types

### LINKED ISSUE #121: storage exploration
- [ ] Filter more directly in the table - like in the column filter or in a row filter?
- [x] consolidate storage yamls into one 
- [x] link to the storage service sections by clicking on the storage table header
- [ ] always show scroll bars, make header stcky

### PR DESCRIPTION
**Pull request by ashleysyg**
This PR fixes the bug in the main storage page (`services/storage`). 
- The issue was it was reading in the entire storage content folder before `storage-tool.yaml` file was added. This caused downstream bugs when looping through the content files because the keys/values are different from the main page content and the storage tool content. 

```
- Changes:
- combine all storage content into `storage-tool.yaml` because it will be easier to update/maintain.
- clean up and fix interfaces and props in all storage components
- put color/icon mapping in the storage types file, and import into storage tool components (needed to add a whitelist to the tailwind config for custom colors - explanation for this is in the tailwind config)
```

### CODE REVIEW

File: components/StorageServiceCard.tsx [hunk 1]
```diff
@@ -1,146 +1,89 @@
...
-const ServiceCard: React.FC<ServiceCardProps> = ({ service, yamlQuestionsConfig, selectedAnswers, isDisabled }) => {
+const StorageServiceCard: React.FC<ServiceCardProps> = ({ service, questionsConfig, selectedAnswers, isDisabled }) => {
 
   // Helper to determine if a service feature's class matches the current selected answer
-  const matchesSelectedAnswer = (featureName: string, featureClass: string | boolean | number): boolean => {
-    const selectedValue = selectedAnswers[featureName];
-    if (!selectedValue) {
-      return true; // No filter for this feature, so it matches
-    }
+  // const matchesSelectedAnswer = (featureName: string, featureClass: string | boolean | number): boolean => {
```
Comment (eldu) [inline components/StorageServiceCard.tsx]: There is a lot of commented out code here?

Comment (eldu) [reply components/StorageServiceCard.tsx]: Does it need to be here or can we remove it?

File: components/ui/form.tsx [hunk 2]
```diff
@@ -1,35 +1,44 @@
...
+            <Markdown
+              rehypePlugins={[rehypeRaw]}
+              remarkPlugins={[remarkGfm]}
+            >
+              {question.information}
+            </Markdown>
+            )
+          }
+
+          {/* {question.information && question.information.length > 0 && (
```
Comment (eldu) [inline components/ui/form.tsx]: same question about commented out code here

**Review by eldu — CHANGES_REQUESTED** [review]
added some questions about the commented out code

File: components/StorageServiceCard.tsx (hunk 1 above)
Comment (ashleysyg) [reply components/StorageServiceCard.tsx]: removed!

File: components/ui/form.tsx (hunk 2 above)
Comment (ashleysyg) [reply components/ui/form.tsx]: also removed

**Comment by ashleysyg** [comment]
I could make a folder `/components/storage` similar to the calendar components and move the storage components into it?

**Comment by eldu** [comment]
> I could make a folder `/components/storage` similar to the calendar components and move the storage components into it?

@ashley i think that would be nice !

**Review by eldu — APPROVED** [review]
approving
